name: Sync the ZAP Service Stats

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  record_stats:
    name: Sync the ZAP Service Stats
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Sync the Stats
      run: |
        python -m pip install pyyaml==5.3.1
        python -m pip install requests
        # Set up AWS CLI
        export AWSCLI_ACCESS=${{ secrets.AWSCLI_ACCESS }}
        export AWSCLI_SECRET=${{ secrets.AWSCLI_SECRET }}
        python -m pip install awscli
        mkdir ~/.aws
        echo "[default]" > ~/.aws/config
        echo "region = us-east-2" >> ~/.aws/config
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWSCLI_ACCESS" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWSCLI_SECRET" >> ~/.aws/credentials

        aws s3 mv s3://project-zap-news/ s3://project-zap/stats/zap-news/ --recursive
        aws s3 mv s3://project-zap-cfu/ s3://project-zap/stats/zap-cfu/ --recursive
        aws s3 mv s3://project-zap-tel/ s3://project-zap/telemetry/raw/ --recursive
